//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("facs ver:0.7.21127.1")]
[assembly: AssemblyDescription("displays file average counts and sizes.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("facs")]
[assembly: AssemblyCopyright("Copyright (C) 2010-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("910D8CD5-0439-4284-A3E4-4192B6BA58B2")]
[assembly: AssemblyVersion("0.7.21127.1")]
[assembly: AssemblyFileVersion("0.7.21127.1")]


