//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("facs ver:1.4.20919.0")]
[assembly: AssemblyDescription("facs")]
[assembly: AssemblyProduct("facs")]
[assembly: AssemblyCopyright("Copyright (C) 2003-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("102A8488-37B8-4837-B28D-B1C1604EE8B1")]
[assembly: AssemblyVersion("1.4.20919.0")]
[assembly: AssemblyFileVersion("1.4.20919.0")]


