//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("facs ver:0.7.31114.3")]
[assembly: System.Reflection.AssemblyDescription("displays file average counts and sizes.")]
[assembly: System.Reflection.AssemblyCompany("Bricksoft.com")]
[assembly: System.Reflection.AssemblyProduct("facs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2010-2013 Kody Brown.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("910D8CD5-0439-4284-A3E4-4192B6BA58B2")]
[assembly: System.Reflection.AssemblyVersion("0.7.31114.3")]
[assembly: System.Reflection.AssemblyFileVersion("0.7.31114.3")]


